### ISSUE TITLE
Hyprland fails to start in a QEMU VM Hyprland 0.45+ aquamarine 5.0  -- black screen no errors

### ISSUE THREAD

**Issue by dwilliam62** [hyprwm/aquamarine#109]
Updating Arch (and NIXOS) to Hyrprland 0.45.* and aquamarine  0.4.5+ resulted in black screen with no errors in a Proxmox QEMU VM.  

Was forced to roll back to older versions to restore function 
![image](https://github.com/user-attachments/assets/90828c93-e774-45fc-a87c-3c5c1a2e212d)

The recent DRM changes seem to be the only ones that might relate to this 
https://github.com/hyprwm/aquamarine/commit/3b00e96f90cb0040de6d88ad99bf5f4d443f0c59

https://github.com/hyprwm/aquamarine/commit/545f506a6331e4a35ec16561c10509bf43bb9328

I tried various combination of hyprland and aquamarine but only rolling back to aquamarine 0.4.3  and hyprland 0.45.0  For NIXOS I had to go back to 0.44.  

Anything newer just results in back screen 
![image](https://github.com/user-attachments/assets/9a8c8e17-683b-4c46-a670-aeb7279aea77)

Normally that screen appears for a few seconds then hyprland loads. 

This is using SDDM for arch, selecting hyprland not hyprland-systemd (which has never worked for me)   In NIXOS I use greetd which also yields the same result. 

I am using Proxmox but others using Virt Manger w/QEMU are reporting the same issues

**Comment by UjinT34** [comment]
AQ > 0.4.5 will work with HL git only.
https://github.com/hyprwm/aquamarine/commit/545f506a6331e4a35ec16561c10509bf43bb9328 before that explicit sync was half functional. Try disabling`explicit_sync_kms` and/or `explicit_sync`.

**Comment by dwilliam62** [comment]
I was using 0.45 and 0.45.1 with AQ   I tried disabling explict_sync and that didn't resolve the issue.  expicit_sync_kms isn't set

**Comment by vaxerski** [comment]
> AQ > 0.4.5 will work with HL git only.

huh? IMO it should work fine once rebuilt.

Can this be bisected? stuff works here.

**Comment by dwilliam62** [comment]
> > AQ > 0.4.5 will work with HL git only.
> 
> huh? IMO it should work fine once rebuilt.
> 
> Can this be bisected? stuff works here.

Are you running in a QEMU virtual machine?    On H/W no issue.   If I update to current builds in NIXOS for example  I get from source via a flake, make no other changes, it fails to start with black screen    In arch when I updated from AUR same issue.  Black screen.

**Comment by UjinT34** [comment]
> huh? IMO it should work fine once rebuilt.

Just assumed that those are pre-built packages which might not be compatible

**Comment by dwilliam62** [comment]
> > huh? IMO it should work fine once rebuilt.
> 
> Just assumed that those are pre-built packages which might not be compatible

They work fine on Hw  And in NIXOS I build frm source 

inputs = {
    nixpkgs.url = "nixpkgs/nixos-unstable";
    hyprland.url = "git+https://github.com/hyprwm/Hyprland?submodules=1"; # hyprland development
    hyprland-plugins = {
      url = "github:hyprwm/hyprland-plugins";
      inputs.hyprland.follows = "hyprland";
    };
So for NIXOS that should be fine correct?

**Comment by fufexan** [comment]
Correct. Also, you don't need submodules anymore, you can revert back to the regular `github:` url.

**Comment by dwilliam62** [comment]
FYI: Another person reported that after upgrading Hyprland/AQ their VMware Workstation VM no longer works.  I asked them to post it as well.

**Comment by dwilliam62** [comment]
Just helped someone on the Hyprland discord with Virtual box to downgrade to 0.44, 0.4.4 and now it works.  Fresh install Arch hyprland   I asked them to post here and provide their info.

**Comment by elenacrs** [comment]
![hyprlanddoesnotwork](https://github.com/user-attachments/assets/0a07cb44-367d-4125-bcb1-0ab8201f7210)
![zoom](https://github.com/user-attachments/assets/8d441566-8db7-4a82-a4d7-cd8ffcd0c36f)

Ive got a fresh arch installation in VMware Workstation VM but when i try to run Hyprland the error in the screenshoots happens... Downgrading both hyprland and aquamarine to 0.4.4 it worked.

That error was not one week ago in the same VMware Workstation VM with another fresh arch installation.

**Comment by mattkasun** [comment]
I have the same issue on bare h/w.  interesting enough, latest version works running in an incus arch container on same hw

[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: endeavour
[LOG] Release: 6.6.62-1-lts
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Sun, 17 Nov 2024 16:35:16 +0000


[LOG] GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 530 [8086:1912] (rev 06) (prog-if 00 [VGA controller])


[LOG] os-release:
NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2021.12.17"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"

[LOG] ========================

**Comment by dwilliam62** [comment]
> I have the same issue on bare h/w. interesting enough, latest version works running in an incus arch container on same hw
> 
 That I have not seen.  Bare metal works fine.  Also like you the VM worked before the update, and if I roll back aquamarine it works

**Comment by vaxerski** [comment]
can someone bisect the exact aq commit that breaks qemu?

**Comment by mattkasun** [comment]
> > > I have the same issue on bare h/w. interesting enough, latest version works running in an incus arch container on same hw
> > 
> > 
> > That I have not seen. Bare metal works fine. Also like you the VM worked before the update, and if I roll back aquamarine it works
> 
> Can you share how you roll back aquamarine after installing Hyprland 0.45.x on Arch and Fedora to make it working again?

i used downgrade 
aur/downgrade 11.4.2-1 (+797 8.35) (Installed)
    Bash script for downgrading one or more packages to a version in your cache or the A.L.A.

Due to dependency of hyprland on aquamarine, had to uninstall hyprland, downgrade aquamarine (0.4.5-1) and then downgrade hyprland(0.45.0.-1)

**Comment by gnussbaum67** [comment]
I believe I have the same issue as above.  Running a NIXOS VM on Virtualbox.
[hyprlandCrashReport2043.txt](https://github.com/user-attachments/files/17882574/hyprlandCrashReport2043.txt)

**Comment by vaxerski** [comment]
Repeating information that is already known or providing more duplicate crash reports will _not_ help this issue.

Please see my comment above.

**Comment by mylinuxforwork** [comment]
> > > > I have the same issue on bare h/w. interesting enough, latest version works running in an incus arch container on same hw
> > > 
> > > 
> > > That I have not seen. Bare metal works fine. Also like you the VM worked before the update, and if I roll back aquamarine it works
> > 
> > 
> > Can you share how you roll back aquamarine after installing Hyprland 0.45.x on Arch and Fedora to make it working again?
> 
> i used downgrade aur/downgrade 11.4.2-1 (+797 8.35) (Installed) Bash script for downgrading one or more packages to a version in your cache or the A.L.A.
> 
> Due to dependency of hyprland on aquamarine, had to uninstall hyprland, downgrade aquamarine (0.4.5-1) and then downgrade hyprland(0.45.0.-1)

aquamarine 0.4.5-1 + hyprland 0.45.0 works for me as well. Thank you so much. 0.45.2 still not working on KVM.

**Comment by adminy** [comment]
I can also confirm that  0.4.4 -> 0.5.0 results in black screen with hyprland and very ramped up spinning fans.

**Comment by JManch** [comment]
#106 is the regressor

**Comment by adminy** [comment]
We might have different issues @JManch as I tried to undo #106 in source code, it still boots broken.

**Comment by b4shful** [comment]
Check if it's fixed in the latest main branch, this might also be fixed by #119

**Comment by dwilliam62** [comment]
I just tried 0.46 and it still doesn't start  Same as before.

**Comment by b4shful** [comment]
@dwilliam62 it's not a fix in HL 0.46 - it's a fix in Aquamarine which was merged like an hour ago - you would need to ensure you are using aquamarine-git (build it from the latest available git commit)

**Comment by dwilliam62** [comment]
I am on NIXOS and I build from source for HL and AQ,  etc using a flake

**Comment by dwilliam62** [comment]
OK I do have an issue on my end.  I can't get AQ to update past 0.4.4.  HL is at 0.46.0 So that won't work! I removed my overrides, the flake.lock is the same as my working bare metal and I tried updating the flake several times   I'll keep working on it

**Comment by dwilliam62** [comment]
![image](https://github.com/user-attachments/assets/6424708f-b795-4f77-89be-cc9899894bd2)

This is all I get when I try to run 0.46 and AQ 0.5.1

**Comment by dwilliam62** [comment]
With Arch and all -git packages it is working 
![image](https://github.com/user-attachments/assets/49a0b201-5430-4469-9357-91eaa9b51875)

Now I need figure out what's up with NIXOS. :(

**Comment by JManch** [comment]
Yeah can confirm this is still an issue on NixOS due to df01de7d6112f48393e89d40c9bde8eeb6b4153d.

Crash with hyprwm/Hyprland@5f1df55fcb45a72e92258113685aa9064f6ebf3e and Aquamarine a132fa41be7ebe797ad758e84d9df068151a723b
[hyprlandCrashReport8303.txt](https://github.com/user-attachments/files/18169938/hyprlandCrashReport8303.txt)
[crash_trace.log](https://github.com/user-attachments/files/18169944/crash_trace.log)

Hyprland does not crash when I apply this patch (reverting df01de7d6112f48393e89d40c9bde8eeb6b4153d)
[patch.txt](https://github.com/user-attachments/files/18169953/patch.txt)
[successful_start.log](https://github.com/user-attachments/files/18169957/successful_start.log)

**Comment by richen604** [comment]
having the same issue with `virtio-vga-gl` drivers as well
looks like the problematic code is [here](https://github.com/gulafaran/aquamarine/blob/df01de7d6112f48393e89d40c9bde8eeb6b4153d/src/backend/drm/DRM.cpp#L1403C1-L1406C6)

was able to reproduce by removing / adding this check
```cpp
    if (!backend->rendererState.renderer) {
        backend->backend->log(AQ_LOG_ERROR, "drm: No renderer attached to backend");
        return false;
    }
```
out of my wheelhouse, but it may be possible that some drivers such as virtgl can handle display directly without a renderer

the benefits of the return might be better situated like so
```cpp
bool Aquamarine::CDRMOutput::commit() {
    // Only check for renderer if we need to do buffer blitting/composition
    if (backend->shouldBlit() && !backend->rendererState.renderer) {
        backend->backend->log(AQ_LOG_ERROR, "drm: No renderer attached to backend when required for blitting");
        return false;
    }
    return commitState();
}
```

**Comment by ikalco** [comment]
@richen604
yeah that makes sense, you can probably open a PR and it'll get merged
just make sure the check is inside commitState() at around line 1523, before blit is done

**Comment by mattkasun** [comment]
still get black screen with extra/aquamarine 0.5.1-2 (342.9 KiB 1.2 MiB) (Installed)

**Comment by dwilliam62** [comment]
> still get black screen with extra/aquamarine 0.5.1-2 (342.9 KiB 1.2 MiB) (Installed)

You need to update hyprland, 0.46.2  & aquamarine 0.5.1-3 and make sure mesa is up to date  Make sure you don't have any -git packages either. (I am assuming Arch?)  

![image](https://github.com/user-attachments/assets/450e740d-936f-4b17-972b-5716e731f0de)


![image](https://github.com/user-attachments/assets/66e75834-8edf-4590-94e6-b79cc7cefd15)

**Comment by mattkasun** [comment]
I had mesa-amber installed.... changed to mesa and it works now.  Thanks

**Comment by dwilliam62** [comment]
> I had mesa-amber installed.... changed to mesa and it works now. Thanks

 You're welcome!    Happy holidays!
